services:
  postgres-db:
    container_name: postgres_db
    image: postgres:14.19
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: cx_txn
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
