services:
  cx-txn-db:
    container_name: cx_txn_db
    image: postgres:14.19
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: cx_txn
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql
    networks:
      - cx-txn-network
    
  dbt:
    container_name: dbt
    image: ghcr.io/dbt-labs/dbt-postgres:1.9.latest
    volumes:
      - ./dbt/cx_txn:/usr/app
    working_dir: /usr/app
    depends_on:
      - cx-txn-db
    networks:
      - cx-txn-network
    command: init cx_txn_dbt


  airflow:
    container_name: airflow
    image: apache/airflow:3.1.2rc1-python3.13
    restart: always
    ports:
      - 8080:8080
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://db_user:db_password@cx-txn-db:5432/airflow
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      # - ./airflow/logs:/opt/airflow/logs
      # - ./airflow/include:/include:/opt/airflow/include
      # - ./airflow/plugins:/plugins:/opt/airflow/plugins
      - ./scripts:/opt/airflow/scripts
      - ./import/csv:/import/csv
    entrypoint: >
      bash -c "
      airflow db migrate && airflow api-server & airflow scheduler
      "
    networks:
      - cx-txn-network
    depends_on:
      - cx-txn-db


networks:
  cx-txn-network:
    driver: bridge


    
  # airflow-db:
  #   container_name: airflow_db
  #   image: postgres:14.19
  #   ports:
  #     - 5434:5432
  #   environment:
  #     POSTGRES_DB: airflow
  #     POSTGRES_USER: db_user
  #     POSTGRES_PASSWORD: db_password
  #   volumes:
  #     - ./postgres/airflow/data:/var/lib/postgresql/data
  #   networks:
  #     - cx-txn-network

  # airflow-init:
  #   container_name: airflow_init
  #   image: apache/airflow:latest
  #   environment:
  #     AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://db_user:db_password@airflow-db:5432/airflow
  #     _AIRFLOW_WWW_USER_CREATE: true
  #     _AIRFLOW_WWW_USER_USERNAME: admin
  #     _AIRFLOW_WWW_USER_PASSWORD: admin
  #   volumes:
  #     - ./airflow/dags:/opt/airflow/dags
  #     - ./airflow/logs:/opt/airflow/logs
  #   entrypoint: >
  #     /bin/bash -c "
  #     airflow db migrate
  #     "
  #   depends_on:
  #     - airflow-db
  #   networks:
  #     - cx-txn-network

  # x-airflow-common:
  #   &airflow-common
  #   image: apache/airflow:latest
  #   environment:
  #     &airflow-common-env
  #     AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://db_user:db_password@airflow-db:5432/airflow
  #   volumes:
  #     - ./airflow/dags:/opt/airflow/dags
  #     - ./airflow/logs:/opt/airflow/logs
  #     - ./airflow/include:/include:/opt/airflow/include
  #     - ./airflow/plugins:/plugins:/opt/airflow/plugins
  #   depends_on:
  #     &airflow-common-depends-on
  #     - airflow-db
  #   networks:
  #     - cx-txn-network